const moodMonth = {
  code: 201,
  success: true,
  msg: '요청에 성공하였습니다.',
  result: [
    {
      isWrited: true,
      diary_id: 1,
      title: '4월 1일 일기',
      date: '2024-04-01',
      content: '오늘 너무 힘들었다. 운영체제 수업은 너무 어렵고 ....',
      main_mood_color: 'B5D3FF',
    },
    {
      isWrited: true,
      diary_id: 2,
      title: '4월 2일 일기',
      date: '2024-04-02',
      content: '오늘은 드디어 감기가 다 나았다. 너무 기뻤다. ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: false,
      date: '2024-04-03',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FEF4A0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'B5D3FF',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FF9191',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'B5D3FF',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FEF4A0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'DBD3FB',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: false,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: false,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: true,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: false,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: false,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
    {
      isWrited: false,
      title: '4월 4일 일기',
      date: '2024-04-04',
      content: '행복하당 ......',
      main_mood_color: 'FBCFE0',
    },
  ],
};

export default moodMonth;
